workflows:
  ios-workflow:
    name: iOS Release Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing settings on Xcode project
        working_dir: app/pushapp/push_demo
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        working_dir: app/pushapp/push_demo
        script: |
          flutter packages pub get
      - name: Generate App Icons
        working_dir: app/pushapp/push_demo
        script: |
          dart run flutter_launcher_icons
      - name: Install Pods
        working_dir: app/pushapp/push_demo
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Build IPA
        working_dir: app/pushapp/push_demo
        script: |
          flutter build ipa --release
    artifacts:
      - app/pushapp/push_demo/build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
